version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1337:5000
    env_file:
      - ./.env.dev
      - ./.env.spotify
    environment:
      - FLASK_DEBUG=1
    depends_on:
      broker-rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
  api-worker01:
    build: ./services/web
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks.celery worker --loglevel=info
    environment:
      - APP_ENV=Dev
    env_file:
      - ./.env.dev
    depends_on:
      - broker-rabbitmq
      - db
    volumes:
      - ./services/web/:/usr/src/app/
  api-beat:
    build: ./services/web
    command: celery -A tasks.celery beat --loglevel=info
    environment:
      - APP_ENV=Dev
    env_file:
      - ./.env.dev
    depends_on:
      - broker-rabbitmq
      - db
  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    env_file:
      - ./.env.flower
    ports:
      - "5556:5555"
    depends_on:
      - broker-rabbitmq
  broker-rabbitmq:
    image: "rabbitmq:3.9.22-management"
    ports:
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 30s
      retries: 10
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=spotify_playlist_lookup
      - POSTGRES_PASSWORD=spotify_playlist_lookup
      - POSTGRES_DB=spotify_playlist_lookup_dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 1s
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
