"""add playlist stat counts

Revision ID: 2eee5b8f283b
Revises: 34c4ee3aec6b
Create Date: 2022-10-05 18:04:07.577478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2eee5b8f283b"
down_revision = "34c4ee3aec6b"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("playlists", sa.Column("track_count", sa.Integer()))
    op.add_column("playlists", sa.Column("follower_count", sa.Integer()))

    op.execute("UPDATE playlists SET track_count = 0")
    op.execute("UPDATE playlists SET follower_count = 0")

    op.alter_column("playlists", "follower_count", nullable=False)
    op.alter_column("playlists", "track_count", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "follower_count")
    op.drop_column("playlists", "track_count")
    # ### end Alembic commands ###
