"""add user generated

Revision ID: 6a630ad5557a
Revises: e8ef61bde5b7
Create Date: 2022-09-09 10:33:28.867831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a630ad5557a'
down_revision = 'e8ef61bde5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('generated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'generated')
    # ### end Alembic commands ###
