"""add track name GIN index

Revision ID: 87c2090face0
Revises: 2eee5b8f283b
Create Date: 2022-10-09 19:49:26.308347

"""
from alembic import op
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '87c2090face0'
down_revision = '2eee5b8f283b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm;"))
    op.create_index('name_idx', 'tracks', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='tracks', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
