"""add user spotify token

Revision ID: b68928fee8b6
Revises: 6a630ad5557a
Create Date: 2022-09-11 12:45:48.105002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68928fee8b6'
down_revision = '6a630ad5557a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_token', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('spotify_token_expires_at', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('spotify_refresh_token', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spotify_refresh_token')
    op.drop_column('users', 'spotify_token_expires_at')
    op.drop_column('users', 'spotify_token')
    # ### end Alembic commands ###
