"""longer playlist description

Revision ID: d9f0475c4459
Revises: b68928fee8b6
Create Date: 2022-09-11 18:41:48.248162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f0475c4459'
down_revision = 'b68928fee8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
