"""add playlist details

Revision ID: e8ef61bde5b7
Revises: 743b32dde3e8
Create Date: 2022-09-03 20:28:30.139077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8ef61bde5b7"
down_revision = "743b32dde3e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlists",
        sa.Column("name", sa.String(length=100), server_default="", nullable=False),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "description", sa.String(length=300), server_default="", nullable=False
        ),
    )
    op.add_column(
        "playlists",
        sa.Column("image_url", sa.String(length=300), server_default="", nullable=True),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "owner_name", sa.String(length=100), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "owner_name")
    op.drop_column("playlists", "image_url")
    op.drop_column("playlists", "description")
    op.drop_column("playlists", "name")
    # ### end Alembic commands ###
